### ISSUE TITLE
요즘 바쁘신가 보네요..!

### ISSUE THREAD

**Issue by woochanleee** [Woomin-Jeon/blog#25]
블로그 종종 구경하곤 하는데 WIL이 2주째 멈춰있는걸 보니 바쁘신것 같네요 :)
재밌게 읽고 있습니당

**Comment by Woomin-Jeon** [comment]
안녕하세요!
요즘 WIL을 작성하는 것에 대한 고민이 있어서 잠시 쉬면서 생각을 해보려고 해요.
보잘 것 없는 글을 읽어주고 계신다니 감사하고 부끄러울 따름입니다 😂

**Comment by woochanleee** [comment]
아하 그렇군요!
매번 방문할때마다 어떻게 이렇게 꾸준히 작성할 수 있는지 놀라곤 했어요 :)
어떤 선택을 하던간에 응원하겠습니다!
